sudo: false

language: node_js

node_js:
  - '0.10'
  - '0.12'
  - 4

before_install:
  - gem update --system
  - gem install compass
  - gem install sass-globbing
  - gem install susy
  - gem install modular-scale

script:
  - npm test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
